### ISSUE TITLE
Inconsistent tag format may be causing failing galaxy installs

### ISSUE THREAD

**Issue by dekimsey** [Frzk/ansible-role-chrony#11]
We've found our ansible-galaxy installs are failing recently and it appears to be related to frzk.chrony's change in tag format.

```
[WARNING]: - frzk.chrony was NOT installed successfully: Unable to compare role
versions (1.0.0, v2.0.0) to determine the most recent version due to
incompatible version formats. Please contact the role author to resolve
versioning conflicts, or specify an explicit role version to install.
ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```

I have a requirements file like such:
```
- src: frzk.chrony
  version: 1.0.0
```

Our builds are unable to execute now and I cannot figure out how to get Ansible to just use the given version. Please advise

**Comment by Frzk** [comment]
Hello,
Thanks for pointing out that issue. This is rather unexpected, I'm sorry that it makes your installs fail :-/
I'll try to fix this somehow as soon as possible.

**Comment by nightspotlight** [comment]
add tag 2.0.0, remove tag v2.0.0

**Comment by Frzk** [comment]
Hello,
Sorry for the delay. I finally replaced the `v2.0.0` tag with `2.0.0` and fixed the release.
Ansible Galaxy has been updated too.
I hope this won't break things for people using the `v2.0.0` tag.
Thanks again for reporting this.
