### ISSUE TITLE
Please do a release of your ansible-role-chrony

### ISSUE THREAD

**Issue by gearboxscott** [Frzk/ansible-role-chrony#4]
Hi,

Nice ansible role, please do a release tag on it so the user can do a version in requirements.yml.  It will help when you make changes and the user can decide to upgrade their code to your new patch or changes on a schedule, not just a thing that happens.

Thank You, GearBoxScott

**Comment by Frzk** [comment]
Hi @gearboxscott,
Thanks for this. I'll definitely do it as soon as the tests are passing again.
I need to invest some time in it.
I'll let this open as a reminder and close it when it'll be done. I hope soon :)

**Comment by Frzk** [comment]
Fixed :)
Thanks again for your interest !

**Comment by srl295** [comment]
@Frzk hi- is https://github.com/Frzk/ansible-role-chrony/commit/a7dd46897834c87e5af8dcd5a2522ca1a510a076 no longer available via ansible galaxy?

**Comment by Frzk** [comment]
@srl295 : I’m afraid it’s not. Is there anything specific to this version that you’re missing with the current one ?

**Comment by srl295** [comment]
> @srl295 : I’m afraid it’s not. Is there anything specific to this version that you’re missing with the current one ?

Nothing specific, just broke my build when it wasn't available

**Comment by srl295** [comment]
> > @srl295 : I’m afraid it’s not. Is there anything specific to this version that you’re missing with the current one ?
> 
> Nothing specific, just broke my build when it wasn't available

Looks like I can work around it with this:

```diff
-- name: frzk.chrony
-  version: a7dd46897834c87e5af8dcd5a2522ca1a510a076
+- src: https://github.com/frzk/ansible-role-chrony
+  version: a7dd46897834c87e5af8dcd5a2522ca1a510a076
+  name: frzk.chrony
```

**Comment by Frzk** [comment]
> Nothing specific, just broke my build when it wasn't available

Oh, I'm sorry to read that :-/

For now on, I'll try to publish the changes in a `development` branch and merge them into `main` along with a new (tagged) release.

Would it work for you ?

**Comment by srl295** [comment]
> > Nothing specific, just broke my build when it wasn't available
> 
> Oh, I'm sorry to read that :-/
> 
> For now on, I'll try to publish the changes in a `development` branch and merge them into `main` along with a new (tagged) release.
> 
> Would it work for you ?

sounds good. It was just the _deleting_ of old items that was a challenge.  In any event, the above workaround worked for me until I can try out your 1.0.0 !
