### ISSUE TITLE
Why does the role update the system timezone?

### ISSUE THREAD

**Issue by bschonec** [Frzk/ansible-role-chrony#8]
Since this is a chrony role I'm confused as to why the role is setting the system time zone.

https://github.com/Frzk/ansible-role-chrony/blob/0d41f4dce9d97b06f47d32ac7cfe1c1fa42871ef/tasks/main.yml#L14

For example, on RHEL8 the system time zone is set to "America/New_York".  That value is incompatible with crony's leapsectz setting.  The leapsectz setting accepts only EST, EDT, UTC, etc.  It does not support the America/New_York style value.

I recommend that setting of the system time zone be remove entirely as this isn't something that chrony should be doing.

**Comment by Frzk** [comment]
Allright, I guess this makes sense :-)

My original idea behind this was to keep some kind of coherence between the system timezone and the one used by Chrony to deal with leap seconds. But I guess it's a bit out of scope after all.

By the way, on Arch Linux the value `America/New_York` **is** accepted by Chrony.

Thanks again :-)
