### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by mlg1** [Frzk/ansible-role-chrony#9]
Hi, Today I noticed that there is no archive to download from github. We have been using the role for several months and before we had no problem installing it. 

```bash
$ ansible-galaxy install frzk.chrony -f
Starting galaxy role install process
- downloading role 'chrony', owned by frzk
- downloading role from https://github.com/Frzk/ansible-role-chrony/archive/master.tar.gz
 [ERROR]: failed to download the file: HTTP Error 404: Not Found
[WARNING]: - frzk.chrony was NOT installed successfully.
ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```

**Comment by Frzk** [comment]
Hi,
I guess this is a consequence of me renaming the `master` branch to `main`.
I just re-imported the role in Ansible Galaxy, I think it should fix your issue.
Please let me know if it's not enough.
Thanks for using this and for the report :)

**Comment by mlg1** [comment]
Hello
Now it works!
Thanks!

**Comment by Frzk** [comment]
Glad to read this, thanks again for reporting the issue :)
